### ISSUE TITLE
How to run PHP command from Host machine to remote PHPFPM container

### ISSUE THREAD

**Issue by nileshadiyecha** [mageinferno/docker-magento2-php#15]
Actually I have installed the Nginx in the Host machine and launched the PHPFPM container with the "https://github.com/mageinferno/docker-magento2-php" guide.

Now the thing is that - I am at host machine's magento-webroot directory and want to run the "bin/magento" from host machine.

So can anyone guide me how to perform this step and what are the configuration I would need to integrate with host and container.

**Comment by markshust** [comment]
If you are using docker-compose setup at https://github.com/mageinferno/magento2-docker-compose, you can use the following line to run magento bin:

```
docker-compose exec phpfpm ./bin/magento
```

I'm closing out this ticket because it's a how-to, but I created a new ticket at https://github.com/mageinferno/magento2-docker-compose/issues/17 to add this to the compose documentation.
