### ISSUE TITLE
Please create a tag at docker.io

### ISSUE THREAD

**Issue by danslo** [mageinferno/docker-magento2-php#30]
Hey there,

I just saw that the versioning was changed (7.0-fpm-0). However, that tag doesn't exist at docker.io (https://hub.docker.com/r/mageinferno/magento2-php/tags/). Could you create it there?

Thanks in advance!

**Comment by markshust** [comment]
Hi @danslo,

Yep -- I prematurely tagged and submitted that release, but am still working out some composer issues at https://github.com/mageinferno/docker-magento2-php/issues/18

Also found another issue https://github.com/magento/magento2/issues/2523 which I'll apply a patch to fix this. The idea is 100% automated composer builds with zero errors :)

I'll update this ticket as soon as I have the build pushed to docker hub and confirmed working.

**Comment by markshust** [comment]
All built:
https://hub.docker.com/r/mageinferno/magento2-php/builds/
https://hub.docker.com/r/mageinferno/magento2-nginx/builds/

Note that these new dir's depend/mount to `/var/www/html` instead of `/srv/www`. The `www-data` user's home directory was `/var/www`, and the simplest change to get all the composer functionality working correctly was to change to this dir.

I just release 5.0.0 of the docker-compose file to https://github.com/mageinferno/magento2-docker-compose -- mainly a ton of fixes for composer. Automated builds with composer and all other composer functionality should now work with zero errors. This also brings back the ability to mount the composer cache from the host to the container, saving a ton of time with installs.
